apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
 name: letsencrypt-pod
spec:
 acme:
  server: https://acme-v02.api.letsencrypt.org/directory
  email: 'lstas180877@gmail.com'
  privateKeySecretRef:
    name: letsencrypt-prob
  http01: {}
